#### 自定义错误处理

```js
class ParamError extends Error {
    constructor(msg) {
        super(msg);
        this.name = "ParamError";
    }
}

class HttpError extends Error {
    constructor(msg) {
        super(msg);
        this.name = "Http Error"
    }
}

function ajax(url) {
    return new Promise((resolve, reject) => {
        if (!/^http/.test(url)) {
            throw new ParamError("请求地址错误")
        }
        let xhr = new XMLHttpRequest();
        xhr.open("GET", url);
        xhr.send();
        xhr.onload = function () {
            if (this.status == 200) {
                resolve(JSON.parse(this.response))
            } else if (this.status == 404) {
                reject(new HttpError("网络请求异常"))
            } else {
                reject("加载失败")
            }
        }
        xhr.onerror = function () {
            reject(this);
        }
    })
}
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
<script src="js/16.js"></script>
<script>
    ajax("huabang.com").catch(err => {
        console.log(err.message)
    })
</script>
</html>
```

